LAB_DESCRIPTION="PROJET DE FIN DE MODULE - ADMINISTRATION RESEAU - DNS + Web Cluster avec Load Balancing"
LAB_VERSION=2.0
LAB_AUTHOR="AGBENONZAN KOSSIVI JACQUES JUNIOR"
LAB_EMAIL="junioragbenonzan31@gmail.com"

#################################
# CLIENTS
#################################

client1[0]=A
client1[image]="kathara/base"

client2[0]=A
client2[image]="kathara/base"

pc1[0]=A
pc1[image]="kathara/base"

#################################
# DNS LOAD BALANCER
#################################

dns_lb[0]=A
dns_lb[1]=B
dns_lb[image]="kathara/base"

#################################
# DNS ROOT CLUSTER
#################################

dnsroot1[0]=B
dnsroot1[image]="kathara/bind:9.11"

dnsroot2[0]=B
dnsroot2[image]="kathara/bind:9.11"

#################################
# WEB LOAD BALANCER
#################################

ws_random[0]=A
ws_random[1]=C
ws_random[image]="kathara/base"

#################################
# WEB SERVERS
#################################

server1[0]=C
server1[image]="kathara/base"

server2[0]=C
server2[image]="kathara/base"